### PR TITLE
Update CloudMonitoringMetricsExporter with the near latest version of OpenTelemetry

### PR DESCRIPTION
**Pull request by TseEnSun**

### CODE REVIEW

**Comment by aabmass** [comment]
@TseEnSun thanks for the PR! Apologies for not looking sooner, I was away on vacation. Any chance you'd like to continue help on this and get the tests passing?

**Comment by TseEnSun** [comment]
@aabmass, Sure, I would like to help, although I already know this implementation will not work correctly. 
How can I see the result of these checks?

**Comment by andaag** [comment]
Why go towards the release candidate of .12 on this instead of the current stable version?

Is the plan here to hold this PR until the full release?

**Comment by TseEnSun** [comment]
> Why go towards the release candidate of .12 on this instead of the current stable version?
> 
> Is the plan here to hold this PR until the full release?

Since [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python) released the 1.0.0 version, they made the metrics API an interval package until 1.12.0rc.  I was trying to integrate with the cloud monitor metrics and open-telemetry. Thus, I tried to implement this by myself and come to this PR.

**Comment by andaag** [comment]
> > Since [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python) released the 1.0.0 version, they made the metrics API an interval package until 1.12.0rc.  I was trying to integrate with the cloud monitor metrics and open-telemetry. Thus, I tried to implement this by myself and come to this PR.

Aha, that explains why I find it so hard to combine these packages and get a working setup. That makes sense 👍. I'll be looking forward to 1.12 then, thanks!

**Comment by JishnuM** [comment]
Sharing that 1.12.0 is out, in case this is unblocked now

**Comment by aabmass** [comment]
Thanks for taking a stab at this. I've opened a separate PR https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/204 and decided to gut some of the code and tests as so much of it is no longer applicable.

**Pull request closed without merging**
