### PR TITLE
add missing copyright headers, change OpenTelemetry copyright to Google

### PR DESCRIPTION
**Pull request by aabmass**
- Add google copyright headers to files missing it
- ~`s/Copyright\ OpenTelemetry\ Authors/Copyright 2021 Google/` – is this ok or should it be put off for later? (@punya)~

### CODE REVIEW

**Comment by punya** [comment]
Please don't change the OT copyrights to Google just yet. I think we'll need to discuss that with the open source program office.

The rest looks good, I'll approve once you revert the OT -> Google changes.

**Comment by ymotongpoo** [comment]
Jumping in here. I suppose when @aabmass copied over the code from `opentelemetry-python` repo (#15), the code was already under CLA, which grants all copyrights to CNCF, so I think we should leave the header as-is.
https://github.com/cncf/cla/blob/master/corporate-cla.pdf

**Comment by aabmass** [comment]
Updated to only add new headers

**Review by punya — APPROVED** [review]
LGTM

**Pull request merged**
