### PR TITLE
Update example codes, the "create_metric" no longer exists.

### PR DESCRIPTION
**Pull request by ysde**
Update example codes, the "create_metric" no longer exists in the latest version.

### CODE REVIEW

**Comment by aabmass** [comment]
@ysde thanks for the PR! Could you fix the lint failure with `tox -e fix` and sign the CLA?

You can ignore the header check :)

**Comment by ysde** [comment]
@googlebot I signed it!

**Comment by ysde** [comment]
Hi @aabmass 
I did `tox -e fix` and got error messages as following:

```
opentelemetry-api~=0.16b1
opentelemetry-sdk~=0.16b1
...skipping...
  Downloading pylint-2.5.3-py3-none-any.whl (324 kB)
Collecting mypy
  Downloading mypy-0.800-cp38-cp38-macosx_10_9_x86_64.whl (9.1 MB)
Collecting Sphinx
  Downloading Sphinx-3.1.2-py3-none-any.whl (2.9 MB)
Collecting sphinx-autodoc-typehints
  Downloading sphinx_autodoc_typehints-1.11.1-py3-none-any.whl (8.7 kB)
ERROR: Cannot install opentelemetry-exporter-google-cloud 0.17.dev0 (from /Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested opentelemetry-exporter-google-cloud 0.17.dev0 (from /Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud)
    The user requested opentelemetry-exporter-google-cloud 0.17.dev0 (from /Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

================================================================================================= log end ==================================================================================================
ERROR: could not install deps [-cdev-constraints.txt, opentelemetry-api, opentelemetry-sdk, -e/Users/arthuryueh/github/opentelemetry-operations-python/test-common, black, flake8, isort, pylint, mypy, -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud, -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-tools-google-cloud, -rdocs-requirements.txt]; v = InvocationError('/Users/arthuryueh/github/opentelemetry-operations-python/venv/bin/python -m pip install -cdev-constraints.txt opentelemetry-api opentelemetry-sdk -e/Users/arthuryueh/github/opentelemetry-operations-python/test-common black flake8 isort pylint mypy -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-tools-google-cloud -rdocs-requirements.txt', 1)
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
ERROR:   fix: could not install deps [-cdev-constraints.txt, opentelemetry-api, opentelemetry-sdk, -e/Users/arthuryueh/github/opentelemetry-operations-python/test-common, black, flake8, isort, pylint, mypy, -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud, -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-tools-google-cloud, -rdocs-requirements.txt]; v = InvocationError('/Users/arthuryueh/github/opentelemetry-operations-python/venv/bin/python -m pip install -cdev-constraints.txt opentelemetry-api opentelemetry-sdk -e/Users/arthuryueh/github/opentelemetry-operations-python/test-common black flake8 isort pylint mypy -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-exporter-google-cloud -e/Users/arthuryueh/github/opentelemetry-operations-python/opentelemetry-tools-google-cloud -rdocs-requirements.txt', 1)
```

**Comment by aabmass** [comment]
@ysde I've seen this sometimes, if you run it again it usually goes away (I think its a pip issue)

**Comment by ysde** [comment]
Hi @aabmass 

I got no luck, I've run it many times but still got the same error.

Thanks

**Comment by aabmass** [comment]
@ysde did you check the "Allow edits from maintainers." box on your PR? I can't push the commit

**Review by aabmass — APPROVED** [review]

**Comment by euri10** [comment]
greetings, not sure if this is normal but I got caught by this reading the docs here: https://google-cloud-opentelemetry.readthedocs.io/en/stable/examples/cloud_monitoring/README.html

seems like either the docs didn't get updated or I'm looking at wrong ones, or anything else possible.

**Comment by aabmass** [comment]
@euri10 thanks for the ping, I have to manually tell it to rebuild the stable tag unfortunately. It should be up to date now 🙂

**Pull request merged**
