### PR TITLE
Update instrumentation sample to use exponential histograms

### PR DESCRIPTION
**Pull request by dashpole**
I'm trying to debug a customer issue with the python SDK + GMP exporter with exponential histograms, so i'm updating the sample to use exponential histograms.

I verified that exponential histogram  can be queried using both MQL and promql (using histogram_quantile).

### CODE REVIEW

**Comment by dashpole** [comment]
I think maybe the self-observability metrics broke.

**Comment by aabmass** [comment]
@dashpole do we want to update all the languages to exponential?

**Comment by dashpole** [comment]
Yes, I have a tracking bug open to do that

**Review by aabmass — APPROVED** [review]
🎉

**Pull request merged**
