### PR TITLE
Remove pragma for undefined type in OTel SDK

### LINKED ISSUE #114: Remove Pragma introduced in #101
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/101/files/688b4bf84ad632635dc91a86628c624f69c89d86#diff-6e7e9495c01b3a91f2e2d9cdb033d1f0c9e032ed3b7b7f7aefbf4f2731d02bb2R416

This can be removed after https://github.com/open-telemetry/opentelemetry-python/issues/1573 is closed.

### PR DESCRIPTION
**Pull request by manojpandey**
Closes #114

### CODE REVIEW

**Comment by aabmass** [comment]
Thanks @manojpandey. I'll merge this after the upstream PR is merged and release 🙂

**Comment by manojpandey** [comment]
Thanks @aabmass

**Comment by aabmass** [comment]
Can rebase this PR? The file was moved to https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/master/opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py

**Comment by manojpandey** [comment]
@aabmass done!

**Review by aabmass — APPROVED** [review]
Thanks!

**Pull request merged**
