### PR TITLE
Don't use `pkg_resources.get_distribution(..).version`

### PR DESCRIPTION
**Pull request by DouglasHeriot**
Similar to discussion at googleapis/python-api-core#27 I am using opentelemetry in an environment where modules are vendored without pip. So, pkg_resources can not be used to search for a module at runtime to get its version.

### CODE REVIEW

**Review by aabmass — COMMENTED** [review]
Can you also update here? https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/8f8d2f0044bac36117089bd881ab902c330a9220/opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py#L98

**Comment by DouglasHeriot** [comment]
Thanks for noticing that. I also found I missed another use in `opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py`.

**Comment by DouglasHeriot** [comment]
This won’t be able to pass the tests until #270 (fix pinning to older `opentelemetry-sdk` version) and/or #269 (update `opentelemetry-sdk` version) are merged.

**Review by aabmass — APPROVED** [review]

**Pull request merged**
